apiVersion: v1
kind: Secret

metadata:
  name: togglemaster-secret
  namespace: togglemaster

type: Opaque

data:

  MASTER_KEY: dG9nZ2xlLW1hc3Rlcg== 

  DB_USERNAME: cG9zdGdyZXM=

  DB_PASSWORD: dG9nZ2xlLW1hc3Rlcg==

  SERVICE_API_KEY: ""

  AWS_ACCESS_KEY_ID: ""

  AWS_SECRET_ACCESS_KEY: ""
